variable "vpc_id" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "key_name" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "ami_type" {}
variable "instance_type" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_size" {}
